### ISSUE TITLE
모바일 화면(320*480)에 대응한다. 

### ISSUE THREAD

**Issue by rladpwl0512** [woowacourse-teams/2022-mo-rak#386]
## (필수) 구현할 기능에 명시한다.
모바일 화면(320*480)에 대응한다. 

## (필수) 구현하는데 필요한 작업을 설명한다.
모바일 화면(320*480)에 대응한다. 
- [x] 랜딩페이지 대응 
 - LandingMainSection에서 background 대신 background-image를 사용해 준 이유 
 ```css
  background-image: url(${Circle});
  background-size: contain;
  background-repeat: no-repeat;
  background-position: bottom 0 right 0;
 ```
